@ECHO OFF
ECHO THIS BATCH IS FOR DEBUGGING THE EXECUTABLE JAR ONLY
ECHO DOUBLE-CLICK THE "demorpg2.jar" TO RUN IT
ECHO -
ECHO Generated by: JAR Maker (http://www.goldenstudios.or.id/)
@ECHO ON
java -jar demorpg2.jar
@ECHO OFF
pause
