@ECHO OFF
ECHO THIS BATCH IS FOR DEBUGGING THE EXECUTABLE JAR ONLY
ECHO DOUBLE-CLICK THE "test.jar" TO RUN IT
ECHO -
ECHO Generated by: JAR Maker (http://www.goldenstudios.or.id/)
@ECHO ON
java -jar test.jar
@ECHO OFF
pause
